# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  ImGui_config = debug
  schiffe_versenken_config = debug

else ifeq ($(config),release)
  ImGui_config = release
  schiffe_versenken_config = release

else ifeq ($(config),dist)
  ImGui_config = dist
  schiffe_versenken_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := ImGui schiffe_versenken

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: ImGui

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C Vendor/imgui -f Makefile config=$(ImGui_config)
endif

schiffe_versenken: ImGui
ifneq (,$(schiffe_versenken_config))
	@echo "==== Building schiffe_versenken ($(schiffe_versenken_config)) ===="
	@${MAKE} --no-print-directory -C schiffe_versenken -f Makefile config=$(schiffe_versenken_config)
endif

clean:
	@${MAKE} --no-print-directory -C Vendor/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C schiffe_versenken -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   ImGui"
	@echo "   schiffe_versenken"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"